import { unsplashSourceUrl } from './images'

export const mockTrips = [
  {
    id: 'mock_goa_ongoing',
    title: 'Goa Beach Vacation',
    destination: 'Goa',
    country: 'India',
    startDate: '2026-05-05',
    endDate: '2026-05-12',
    travelers: 2,
    budget: 48000,
    status: 'ongoing',
    summary: 'Beach time, water sports, sunset cruise, and local seafood spots.',
    image: unsplashSourceUrl('goa india beach travel', 'goa'),
    type: 'Vacation',
  },
  {
    id: 'mock_kerala_ongoing',
    title: 'Kerala Family Trip',
    destination: 'Kerala',
    country: 'India',
    startDate: '2026-05-08',
    endDate: '2026-05-15',
    travelers: 4,
    budget: 62000,
    status: 'ongoing',
    summary: 'Backwaters, tea plantations, and relaxed houseboat stay.',
    image: unsplashSourceUrl('kerala india backwaters travel', 'kerala'),
    type: 'Family',
  },
  {
    id: 'mock_tokyo_upcoming',
    title: 'Tokyo Adventure',
    destination: 'Tokyo',
    country: 'Japan',
    startDate: '2026-06-10',
    endDate: '2026-06-20',
    travelers: 1,
    budget: 210000,
    status: 'upcoming',
    summary: 'City exploration, day trips, theme parks, and street food tours.',
    image: unsplashSourceUrl('tokyo japan city travel', 'tokyo'),
    type: 'Adventure',
  },
  {
    id: 'mock_paris_upcoming',
    title: 'Paris Vacation',
    destination: 'Paris',
    country: 'France',
    startDate: '2026-07-02',
    endDate: '2026-07-10',
    travelers: 2,
    budget: 180000,
    status: 'upcoming',
    summary: 'Iconic sights, museums, cafés, and river cruise evenings.',
    image: unsplashSourceUrl('paris france eiffel tower travel', 'paris'),
    type: 'Vacation',
  },
  {
    id: 'mock_swiss_upcoming',
    title: 'Switzerland Tour',
    destination: 'Zurich',
    country: 'Switzerland',
    startDate: '2026-08-08',
    endDate: '2026-08-16',
    travelers: 2,
    budget: 260000,
    status: 'upcoming',
    summary: 'Scenic trains, alpine towns, lakeside walks, and mountain views.',
    image: unsplashSourceUrl('switzerland alps travel', 'swiss'),
    type: 'Tour',
  },
  {
    id: 'mock_bali_completed',
    title: 'Bali Honeymoon',
    destination: 'Bali',
    country: 'Indonesia',
    startDate: '2025-08-14',
    endDate: '2025-08-21',
    travelers: 2,
    budget: 150000,
    status: 'completed',
    summary: 'Resort stay, beach clubs, temples, and spa relaxation.',
    image: unsplashSourceUrl('bali indonesia beach travel', 'bali'),
    type: 'Honeymoon',
  },
  {
    id: 'mock_dubai_completed',
    title: 'Dubai Business Trip',
    destination: 'Dubai',
    country: 'United Arab Emirates',
    startDate: '2026-03-05',
    endDate: '2026-03-08',
    travelers: 1,
    budget: 175000,
    status: 'completed',
    summary: 'Meetings, skyline views, desert safari evening, and marina dining.',
    image: unsplashSourceUrl('dubai uae skyline travel', 'dubai'),
    type: 'Business',
  },
]

