export const mockDestinations = [
  {
    id: 'india_taj_mahal',
    name: 'Taj Mahal',
    country: 'India',
    rating: 4.8,
    description: 'Iconic white-marble mausoleum and one of the world’s most famous monuments.',
    estimatedBudget: 650,
    imageUrl: 'https://source.unsplash.com/1600x900/?taj%20mahal,india',
  },
  {
    id: 'india_goa_beaches',
    name: 'Goa Beaches',
    country: 'India',
    rating: 4.6,
    description: 'Palm-lined beaches, water sports, and vibrant nightlife by the Arabian Sea.',
    estimatedBudget: 900,
    imageUrl: 'https://source.unsplash.com/1600x900/?goa,beach',
  },
  {
    id: 'france_eiffel_tower',
    name: 'Eiffel Tower',
    country: 'France',
    rating: 4.7,
    description: 'Paris landmark with panoramic city views and glowing night illuminations.',
    estimatedBudget: 1800,
    imageUrl: 'https://source.unsplash.com/1600x900/?eiffel%20tower,paris',
  },
  {
    id: 'japan_tokyo_tower',
    name: 'Tokyo Tower',
    country: 'Japan',
    rating: 4.5,
    description: 'A classic Tokyo viewpoint with neon city vibes and nearby attractions.',
    estimatedBudget: 2200,
    imageUrl: 'https://source.unsplash.com/1600x900/?tokyo%20tower,japan',
  },
  {
    id: 'indonesia_bali',
    name: 'Bali',
    country: 'Indonesia',
    rating: 4.6,
    description: 'Tropical island escapes: beaches, temples, rice terraces, and serene resorts.',
    estimatedBudget: 1600,
    imageUrl: 'https://source.unsplash.com/1600x900/?bali,beach',
  },
  {
    id: 'uae_dubai_marina',
    name: 'Dubai Marina',
    country: 'United Arab Emirates',
    rating: 4.6,
    description: 'Modern waterfront skyline, luxury dining, and vibrant city nightlife.',
    estimatedBudget: 2400,
    imageUrl: 'https://source.unsplash.com/1600x900/?dubai,marina',
  },
]

export const mockPreviousTrips = [
  {
    id: 'prev_goa',
    destination: 'Goa Trip',
    country: 'India',
    startDate: '2025-12-18',
    endDate: '2025-12-24',
    budgetSpent: 520,
    travelers: 3,
    status: 'completed',
    imageUrl: 'https://source.unsplash.com/1600x900/?goa,beach',
  },
  {
    id: 'prev_paris',
    destination: 'Paris Vacation',
    country: 'France',
    startDate: '2025-10-02',
    endDate: '2025-10-09',
    budgetSpent: 1850,
    travelers: 2,
    status: 'completed',
    imageUrl: 'https://source.unsplash.com/1600x900/?paris,eiffel',
  },
  {
    id: 'prev_tokyo',
    destination: 'Tokyo Adventure',
    country: 'Japan',
    startDate: '2026-01-12',
    endDate: '2026-01-20',
    budgetSpent: 2300,
    travelers: 1,
    status: 'completed',
    imageUrl: 'https://source.unsplash.com/1600x900/?tokyo,city',
  },
  {
    id: 'prev_bali',
    destination: 'Bali Honeymoon',
    country: 'Indonesia',
    startDate: '2025-08-14',
    endDate: '2025-08-21',
    budgetSpent: 1600,
    travelers: 2,
    status: 'completed',
    imageUrl: 'https://source.unsplash.com/1600x900/?bali,resort',
  },
  {
    id: 'prev_dubai',
    destination: 'Dubai Business Trip',
    country: 'United Arab Emirates',
    startDate: '2026-03-05',
    endDate: '2026-03-08',
    budgetSpent: 2100,
    travelers: 4,
    status: 'completed',
    imageUrl: 'https://source.unsplash.com/1600x900/?dubai,skyline',
  },
]
